import type { ComponentDefinition } from "@/registry/types";
import { antDesignComponentDefinitions } from "./ant-design-definitions";

const ezyrFoundationDefinitions: readonly ComponentDefinition[] = [
  {
    id: "Frame",
    displayName: "Frame",
    description: "Canvas container for pages, screens, and nested layouts.",
    icon: "box",
    category: "layout",
    taxonomy: "layout",
    version: "1.0.0",
    defaultProps: {},
    defaultStyle: {
      minHeight: "100vh",
      overflowX: "hidden",
      overflowY: "visible",
    },
    editableProps: ["width", "padding", "background"],
    events: [],
    slots: ["children"],
    childrenRules: { minChildren: 0 },
    canvas: {
      draggable: true,
      droppable: true,
      nestable: true,
      acceptsChildren: true,
    },
    runtime: { mode: "rendered" },
    editing: { panel: "standard" },
    composition: { allowedParents: ["Frame", "Section"], minChildren: 0 },
  },
  {
    id: "Section",
    displayName: "Section",
    description: "Responsive layout section for grouped content.",
    icon: "box",
    category: "layout",
    taxonomy: "layout",
    version: "1.0.0",
    defaultProps: {},
    editableProps: ["width", "padding", "background", "radius"],
    events: [],
    slots: ["children"],
    childrenRules: { allowedParents: ["Frame", "Section"], minChildren: 0 },
    canvas: {
      draggable: true,
      droppable: true,
      nestable: true,
      acceptsChildren: true,
    },
    runtime: { mode: "rendered" },
    editing: { panel: "standard" },
    composition: { allowedParents: ["Frame", "Section"], minChildren: 0 },
  },
  {
    id: "Text",
    displayName: "Text",
    description: "Typography block for headings and body copy.",
    icon: "type",
    category: "content",
    taxonomy: "content",
    version: "1.0.0",
    defaultProps: { text: "Text", level: "body" },
    editableProps: ["text", "level", "color", "align"],
    events: [],
    slots: [],
    childrenRules: { maxChildren: 0 },
    canvas: {
      draggable: true,
      droppable: false,
      nestable: false,
      acceptsChildren: false,
    },
    runtime: { mode: "rendered" },
    editing: { panel: "standard" },
    composition: { maxChildren: 0 },
  },
  {
    id: "Button",
    displayName: "Button",
    description: "Action trigger with workflow events.",
    icon: "mouse-pointer",
    category: "input",
    taxonomy: "interactive",
    version: "1.0.0",
    defaultProps: { text: "Button", variant: "primary", size: "middle" },
    editableProps: ["text", "variant", "size", "disabled", "loading", "events"],
    events: ["click", "dblclick", "hover", "focus"],
    slots: [],
    childrenRules: { maxChildren: 0 },
    canvas: {
      draggable: true,
      droppable: false,
      nestable: false,
      acceptsChildren: false,
    },
    runtime: { mode: "rendered" },
    editing: { panel: "standard" },
    composition: { maxChildren: 0 },
  },
  {
    id: "Image",
    displayName: "Image",
    description: "Accessible image with source and alt text.",
    icon: "image",
    category: "content",
    taxonomy: "content",
    version: "1.0.0",
    defaultProps: { src: "", alt: "" },
    editableProps: ["src", "alt", "fit", "radius"],
    events: [],
    slots: [],
    childrenRules: { maxChildren: 0 },
    canvas: {
      draggable: true,
      droppable: false,
      nestable: false,
      acceptsChildren: false,
    },
    runtime: { mode: "rendered" },
    editing: { panel: "standard" },
    composition: { maxChildren: 0 },
  },
  {
    id: "Form",
    displayName: "Form",
    description: "Input group with submit workflow hook.",
    icon: "form-input",
    category: "input",
    taxonomy: "data-entry",
    version: "1.0.0",
    defaultProps: {},
    editableProps: ["layout", "submitText", "events"],
    events: ["submit"],
    slots: ["children"],
    childrenRules: { minChildren: 0 },
    canvas: {
      draggable: true,
      droppable: true,
      nestable: true,
      acceptsChildren: true,
    },
    runtime: { mode: "rendered" },
    editing: { panel: "mini-builder", miniBuilderId: "form-builder" },
    composition: { minChildren: 0 },
  },
];

export const coreComponentDefinitions: readonly ComponentDefinition[] = [
  ...ezyrFoundationDefinitions.filter(
    (definition) =>
      !antDesignComponentDefinitions.some(
        (antDefinition) => antDefinition.id === definition.id,
      ),
  ),
  ...antDesignComponentDefinitions,
];
