import type { ComponentDefinition } from "@/registry/types";
import { antDesignComponentDefinitions } from "./ant-design-definitions";

const ezyrFoundationDefinitions: readonly ComponentDefinition[] = [
  {
    id: "Frame",
    displayName: "Frame",
    description: "Top-level app or page container.",
    icon: "box",
    category: "layout",
    version: "1.0.0",
    defaultProps: {},
    editableProps: ["width", "padding", "background"],
    events: [],
    slots: ["children"],
    childrenRules: { minChildren: 0 },
  },
  {
    id: "Section",
    displayName: "Section",
    description: "Responsive layout section for grouped content.",
    icon: "box",
    category: "layout",
    version: "1.0.0",
    defaultProps: {},
    editableProps: ["width", "padding", "background", "radius"],
    events: [],
    slots: ["children"],
    childrenRules: { allowedParents: ["Frame", "Section"], minChildren: 0 },
  },
  {
    id: "Text",
    displayName: "Text",
    description: "Typography block for headings and body copy.",
    icon: "type",
    category: "content",
    version: "1.0.0",
    defaultProps: { text: "Text", level: "body" },
    editableProps: ["text", "level", "color", "align"],
    events: [],
    slots: [],
    childrenRules: { maxChildren: 0 },
  },
  {
    id: "Button",
    displayName: "Button",
    description: "Action trigger with workflow events.",
    icon: "mouse-pointer",
    category: "input",
    version: "1.0.0",
    defaultProps: { text: "Button", variant: "primary", size: "middle" },
    editableProps: ["text", "variant", "size", "disabled", "loading", "events"],
    events: ["click", "dblclick", "hover", "focus"],
    slots: [],
    childrenRules: { maxChildren: 0 },
  },
  {
    id: "Image",
    displayName: "Image",
    description: "Accessible image with source and alt text.",
    icon: "image",
    category: "content",
    version: "1.0.0",
    defaultProps: { src: "", alt: "" },
    editableProps: ["src", "alt", "fit", "radius"],
    events: [],
    slots: [],
    childrenRules: { maxChildren: 0 },
  },
  {
    id: "Form",
    displayName: "Form",
    description: "Input group with submit workflow hook.",
    icon: "form-input",
    category: "input",
    version: "1.0.0",
    defaultProps: {},
    editableProps: ["layout", "submitText", "events"],
    events: ["submit"],
    slots: ["children"],
    childrenRules: { minChildren: 0 },
  },
];

export const coreComponentDefinitions: readonly ComponentDefinition[] = [
  ...ezyrFoundationDefinitions.filter(
    (definition) =>
      !antDesignComponentDefinitions.some(
        (antDefinition) => antDefinition.id === definition.id,
      ),
  ),
  ...antDesignComponentDefinitions,
];
